# Generated by Django 4.0.2 on 2022-03-19 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_number', models.IntegerField()),
                ('words_number_with_spaces', models.IntegerField()),
                ('words_number_without_spaces', models.IntegerField()),
                ('letters_amount', models.IntegerField()),
                ('foreign_words_amount', models.IntegerField()),
                ('punctuation_marks', models.IntegerField()),
                ('classic_nausea', models.FloatField()),
                ('academic_nausea', models.FloatField()),
                ('water_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('analyzeResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer_api.analyzeresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
