# Generated by Django 4.0.2 on 2022-03-19 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer_api', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='UserText',
        ),
    ]
